public class Day19TestData {

    public static String inputExmaple1 = "r, wr, b, g, bwu, rb, gb, br\n" +
            "\n" +
            "brwrr\n" +
            "bggr\n" +
            "gbbr\n" +
            "rrbgbr\n" +
            "ubwu\n" +
            "bwurrg\n" +
            "brgr\n" +
            "bbrgwb";

    public static String inputData = "rwu, bubw, wbwb, buwwuw, rrwrw, wbb, bgbb, wugbrr, brrw, rb, rwbw, bwgb, uub, ubrguw, rbwrwbur, rrgbw, urgw, urr, buugww, ggg, guu, rgwuu, rbwuu, ugugbgr, ugr, wbbu, bgg, rgr, rbbubw, bwrbgww, bbgurbr, b, wgubgw, rrw, rww, gbu, wwwbu, uwwg, uuuu, gbb, wrwggb, urgubb, rwr, bbw, urbuw, bg, grguu, guwbw, bwuuw, bu, uwruu, ruwg, grwbg, wbrb, rwgwrgu, wguuu, wuu, rur, br, wwg, ugrubb, gwwubbwb, wwgwuur, rwwrbbb, wgg, bggg, uubuu, guuwur, bbwwuguw, rgwwgw, rgrrrwur, wwgr, wwurgb, uuruw, bwg, bwwwwgw, gwrbww, wgw, uwrw, rubwb, rbb, gubwgb, guwubgg, bugg, gwu, ubgrr, uuwbwu, gg, ggu, rrubw, rbg, rwg, rrwgu, wguwb, brubugg, gurgrr, uuw, guggrg, brr, gww, bbwb, rrwrg, uggbbr, brbwg, wubr, urgg, brw, uwwug, wugbrw, gbgrb, bwwggg, wgubur, guuggw, brwr, urbr, uurrwrw, rrb, wggguw, brugrwg, wubrb, ubb, brggw, uuur, wubrgbr, wbwg, rwugur, gwg, wgb, uubr, ww, rgg, rwuwgur, uru, uwu, gwr, ru, uwrr, ubrwwr, bwgbgg, bwrw, grr, bbb, w, wrbgrg, bbwbgb, rwb, wwgrb, rub, bubr, wb, gwbuwwbr, bwgwrb, guw, wwb, urg, ubgu, rwuuub, rg, wuw, bwr, bw, rwuw, rggr, buwu, uu, uw, bbugb, bubbb, uuu, grrb, wwbw, rbrbu, rwwrb, bgr, brb, wrrrggw, gw, bgb, wguww, rgug, wgu, wbugwbuw, ggb, rbrg, buur, gub, rbu, bgub, ggw, rw, rggbgrbw, grbb, gbbb, ubgbg, gbr, uww, gwurb, rrwg, ubg, uwwrwuub, gbwwg, ruw, wbuwu, bbrg, grrg, gbrrr, wwu, bgwgb, wuwgbuwu, bbu, gwb, rrwrbbrr, wbg, wrww, gru, uuguug, wbubrg, rbggr, bwwb, ruu, wbww, rbrbr, rgwgrwuu, bgur, rgbbuu, ubu, urbwru, urbgb, gbg, rbrb, wu, u, rruwu, rrrrb, ubbru, urwubr, urrb, bug, wwrrrbb, rgw, rwuu, wrbu, brg, rggg, rrggw, rwuuwb, bruww, wrgb, ruruuwwu, bbrugrwb, bur, buw, wrrg, g, wbbbwgb, gur, ggwgg, ugbg, rrr, ug, bub, ugbr, uwwuu, ugwrwr, buu, wugb, rbrr, bbgw, wbgbg, gwuw, uug, ggbr, bggrb, ugru, uwuw, ugw, wgwrrwr, wrgrb, rbrgg, gu, uugwuub, wuwrw, uwg, gwwrbb, gbbrb, wrg, rguuur, gwuwrwgg, ugrwr, ururb, wwgwbg, wgwu, wgbwu, rubwwr, bwrg, wbr, ggr, uwwu, wuuwgrr, ruurrugb, grugrub, rrurb, rgb, ubwwurr, wgbubgw, ugu, bbub, gubu, bugw, ggrww, ugwr, wrw, brgb, rgbrgru, ugguwb, brwrubu, grw, gbrr, bgu, uwr, uuru, wgbr, bruw, gwwr, gbgw, wgbubggg, bgrg, ubwrg, wrb, rwgwg, grgb, ubuuu, wr, ub, bb, bru, bbwrgr, wuuubuw, rgru, rgugguw, gug, wwubwu, wgbbw, ruwwwgw, wgr, brbuuu, rbwrbr, ruuuub, gb, wrbwwbg, bruug, wgug, urb, rru, gr, gbrwgw, wrr, rubug, bgguw, gwgr, wwub, rwrrg, bgubrr, urgwg, wwr, www, brrubg, ugrrg, wurugguw, wur, uwrwrg, rrg, bwgrr, gbggbb, wrrggwr, rr, gguu, wru, wbu, wuuuubw, ugb, rgwuwuuw, bwb, gbrgbg, gwugb, gbggguww, uurrggw, wrwr, bwu, bbr, ggwggwu, bbrubw, ubw, gbw, bbwggbu, rbbbg, ruubw, guwb, rruwbg, rgwr, wrggr, rbr, rgu, gwwbw, wruwg, rugggug, grg, ruuwu, wbub, uwug, rwbgggw, uwbb, urw, rrggrg, urwg, burwbw, rbgb, bbg, ugugurr, wug, guuw, ugg, wbw, gbwwr, uwb, rgbg, gbbu, bww, brugwug, wrwwwrr, rurbgbgb, ugwu, ubwuggu, bgw, urrbb, bgbug, ubr, gurg, wwbwww, buwug, wrrwgbb, wuub, rwru, wggubw, bgrw, grgu, brbrgg\n" +
            "\n" +
            "brbgbrurbgbgbrwwggwuuwwbrbwuuwuwwugbubwuwwuruwuburbwuur\n" +
            "wgbwgwgugwgwgrwbwbrrugubwbrgwuwuuwugrwuur\n" +
            "uwuggwwrwuwbuuwugurwbwggwurgbbwbgugrrubbgwbuwgbwgwwurgwb\n" +
            "bwggggwwrwwgbrrurwggwwwwuwggbbrrwrwruruburbrgbr\n" +
            "rrwububwbugrruurwuwrwbggwbugwwwruuwrbbugbwrrbuwrwrurw\n" +
            "bbgrbuwwrgwgwuburwgubrwuwrbguggwurgbbgwrwbubggbrwrrbwuuu\n" +
            "wbwuwbggubbgbbbbubgwgwrgwuubguwubgubwwggguwubuwuugrbggwuw\n" +
            "bwugbgruurbburuwgggbubbgbbggbguburgwbgwbrgbwugrbwbuugw\n" +
            "grrwurwwwruwurrgrubbrbwgubwgbrrgburwugwggwwrwb\n" +
            "uwwbwgbwruwbwgwwggrbugwgbbrbrwruuububwbwrurugwwgwwwwwuur\n" +
            "gbuwrbwrwwbbuwwurbbgwbwwuwbwwruurbbruwruwbgrwbgrrgwwbbwr\n" +
            "ugrgbrggrwugugwbrwbbwwbrwrbuuuwubuwrruur\n" +
            "bwwrruurgubwrgrguuwwbwrbuwggbwgrbrbbugbwugggrwbgur\n" +
            "wwbggbbwubbbbwbbgrgggrrgrrwbwgwgubwwrguwrwwrbubuuruggw\n" +
            "uwrbwuggugubbubbrubwgruuugbrbuwgbugwgbbuuggwwwbwwr\n" +
            "ugwrgwbrrwwbuguubguwwubugwgbrbbwrwbubrgbggbwgwbwb\n" +
            "ugurbbrwwrwwrbbwugbguwuwgwbuuwguubwwbuwwggbrruwbwugwg\n" +
            "rbwbbubrurbwrwrwurbbwwrggggrrbbwwrgrggruwbuuwwwuubuu\n" +
            "bwubuwuwrurbwggbburbrbgwrruruuwbbuuwwrggbgrbwurrb\n" +
            "wrbuguuwugbrrwbrugbbrgbugrwuugubwugwwbubruwruurruu\n" +
            "wbugwubuwbwugrrbggbgruuwgrruwgrbguuwrbgrguurw\n" +
            "wbguwurwrwbbuurubrbgbbrwwburrrbbrggwrrruwbgbbrrgwubuug\n" +
            "brrrwbwuwgrbrrurwwbugrwwbgguuwubbrwuuruwbgurggbbubbguur\n" +
            "ububbuwggguwwuguggguwbrurwubuwurwubwwrbubrrwgggwgb\n" +
            "ggwgbrgbrugrgrrurrrrbgbgbwbbgwuubuurwruwruur\n" +
            "buurugrwrwgrbuubwubbwbgwwbwwuwuubrrrruuurwuuubgwwgubrrrrwuur\n" +
            "gugubwbgrbrgwuuuwgrgrgrwwrrbgrgwugwgwbbwuwrwggbwgwg\n" +
            "rugruugwwgwbwwburuugwwgubwrgrrrwurrgbwuur\n" +
            "ggbbggbbgubwggrbuwbubrurgwbwgrruwwgwbgubub\n" +
            "gggwurrgwuwuuwrrrbrwrwwrwbgwwrbgwrubbwugbgwgwggguugggbg\n" +
            "rwbggrbbrrubrbgggrrbrgrgrwrgburubbuuubruurrrurgwbugrbr\n" +
            "uugbwwrgwrrbrrugrbbuuwbuuggrrwwrwbgbbrguuruwrbbgruubw\n" +
            "buwbbbgwwrrrggbrwubrwbbbrwwugbwgggwruuuubwbgbbru\n" +
            "uwwwgwbgwwwrbguwbgrbwrwguwrrrgwrwrbgrgruurrggrwgbbuw\n" +
            "uwwbuuwrurrbugugbgruwrggbuububugggurubrwbugrruggurgwruur\n" +
            "brbuuwwbugubgrbwwwrbgggruurrwurgbwrwwguruwbr\n" +
            "bbrgrbbruuugwbwuurrrrgubgburwuubgbwgrugbugbgurugwwgrrrwwuur\n" +
            "burwgrrgwgwwrbbgubwwbwruwgwugbwgugrrurgrbrubwugbu\n" +
            "ggwwuwgwwggrwwurwrgwwbgurwgbugrrgugbrubrwwuwguugrwwggbgru\n" +
            "uurrgbbbwrwbwgburgrwwgugbbgruurwbugguguwrurggbuwuwrbw\n" +
            "uwbuwrruuuwbbguwbgrwwgbuguugubuuwrurwuwrbbr\n" +
            "rgwruwgubbwrrruburbbgbguubrwbwwgbuwgrgwububrwgrwwrwwbuuuu\n" +
            "ggrgrwurwuuwbwrbwrugurwbwurrbbwbrbruruur\n" +
            "ubrggwgruuuurrwrguwggwgbuwggggwwwrgwbgbwbguu\n" +
            "wrwwrgbbbgruwrbubbbrrbbrbrwrwwubuggrbuuwwuwwrwubbggbbwbwuur\n" +
            "bwwgugbrgbggrgwguwurrwubuggbguruwwrgrwuwwburrburgrgwb\n" +
            "gwubugrgurbbgbubgbwgrubbwbgubgrubgrgbruubggwwwgr\n" +
            "rrggrubrbugubrbuburrgbubuurugbgrrugwgbrrrwubbggww\n" +
            "rurwbgbgwbwrbburubruubrbwgrrrbbrbrurububwgwwugbwg\n" +
            "wbgbgrrrgwgrwbrwuwwuuuurubrrbgwwwbrbgbuwwgbbrrbgrrggbb\n" +
            "wbgwbrgrrbbwrwbrggwwwrbrurbgbuggurgrwrgwrwuwr\n" +
            "wrrbrgbwrugrgwuubuubguwguubwrgugbggwgurbugbrrubbrrgrbu\n" +
            "ruubgrgrgrurbrgugugbbwrrwuwbwuwwwwuwbgbrgrrrbrubb\n" +
            "urwbbwwgbugwgurbrgwruggwugbburbbwrgubugwwrugwubrg\n" +
            "uwurgbuwuuwgwubwgwuwwgbubgwrgbgrrrbubwgwgbwwgbgb\n" +
            "bbgwrrugbgrwrrgwggubwrurwwrgubrrbrwubrbwrwwrbrr\n" +
            "burwbwuurrgbbbrgrwuubuwwwuwgbrgruwgwrgrgbgrwgu\n" +
            "buwgwrbbrguwrgruwguwrrwugbbwgggggwrbwubrur\n" +
            "rubgruggggubrbwgbggwugwgggrgrurwgbrgbbrbbbrgub\n" +
            "ugurruwuggbrrugrbbwgwrgrurbwwgrbrbwurwuurbrubwurug\n" +
            "wuguurubruguuwwggbgwrrrgrrurwrwgrgugrrbbbubgrwuguub\n" +
            "ugbrbwrwuugrgwbwubbubuwwgwrgbugbgurbuwrwgwb\n" +
            "rbrrburrbwwgbrururrggrbubrgburwwwbwrgrwbrrrggwgbguuug\n" +
            "uugwggrwuwbgwrrgugbwwwbuwrrbgwwugbuwggrugbuuw\n" +
            "ubgrugbbwuwgbuwugbggubrugwuurugwbgrgugrwrruwguur\n" +
            "guwbruuuurbgruwbguwwgwbugbwrbrbgbwrguwbwrurwwb\n" +
            "bwwwrwbbwrwbbuubgrbggguwgwubgwrrwubggrgubwwbwruur\n" +
            "wwgwubwbbuwgwbgubbwruwrbrbururrbruwugggggbwubrrwwgwuw\n" +
            "brrwgwrubrugggrbuubgbbbbwuuurrbgwwrgrrbbuugbgwwbgrr\n" +
            "wubgugguugwgrwbwuwubgbwguwgrgggugburrruwguur\n" +
            "buuuugwggwgwgbgubbwbrbwrwburuwwuubbwrwgguur\n" +
            "wwgbggwrrrgbgggbwgbubggggbuurrrruwbwbbbgbbggwwgrugruur\n" +
            "buguwwwrbruubuubgrgrruguugggrbgwwuwuggwgrubbgwrwbuub\n" +
            "gbruurruurwgbubgggwggubbwuwugbbgwwubbrrrrbruwwbwwrrwwbggw\n" +
            "bugrgwuwwbrurggwwubbwbuwwgrrurgbrwbggwugbrruur\n" +
            "urggwgbrbbuwrrbgruuuugurrurwrgbgwrbgbrgurwwb\n" +
            "ubrwbgugbuwuwwwwwrwugwbwbbuuuuubwwwbgwggwb\n" +
            "uwrbbbrgwrugrrgurugwuruwrubgrwuruwuurwubrbg\n" +
            "uwrbugrrrbugggwurrbgrugrrgbuurguwuwrgbbwbrww\n" +
            "wrrgwgbgugrruguwrrwbbwugburrwwrwbuggbuuubbrbruuguuggurgwbw\n" +
            "rrugggbggbuwwgurubwgbbwwuwbuwwrguugbrbbbrugrr\n" +
            "wuwgguuggwugguwwrrugbrburrgbburuwwuubwggwuwgbuwurrg\n" +
            "wbwgbbuurgbbrgrrurwwrbrrwgrrrwbbggwbbrgurugwwrbgrbgrgb\n" +
            "rggbubwrrbrwuruuwwwrgugguwrrrbugwwrgggbbuggwugwbrwruwgw\n" +
            "ruuwrwburgrwwrrrrwrbbrrwwbgbubuuwguubrgrgbrbwrrruwrbrub\n" +
            "ruwrubbugrugwggwrbwrrgwuwgubuuruuggrgubwugwugbwbrgbruur\n" +
            "rrwururuuwwbrbgrururrwrbrgubbrbwwgububgbruubguuurww\n" +
            "rruubrbrrbggwrruwrgwguwgburbbbggubugwuurrrbbwbwwu\n" +
            "rugwubgbgurgwbuwbrbubwgbuugwubgbuuggbwuuwubrbrgrwwrgggu\n" +
            "wrugrwrggbugbbbrbwwubbwuubrgwrwgrrrwbububbw\n" +
            "brbrbrwwwrbrrgrwwbrrbbubwwwwburugbrgwrwruuubggugr\n" +
            "rbggwguugubuurugrgbggbggbrbwruwguwurguwuububrrwrguggwrbgg\n" +
            "rrggrgrugbrbgrbwwwrbrwrgubuwguwrwburbwbgwgr\n" +
            "ggwrgwruwgruurrugbbgrwwguubrggwwbgrbwwggbbruwugubbgbuw\n" +
            "wwrwgrbrbgbwgwwguwwwuubwrbuwbrggbrbrwwwwruwuur\n" +
            "rwggubwgrbrbbbwbrgbbrubruuuwrwuugwwugurbwugrwbgrwuubub\n" +
            "bwrrwgubgwbwbbugbubrgwgbbrbbbwgugbbugugwgrgubrwr\n" +
            "bwbgrbbgbbbrwburgrgrrrrubwurbbubbwuwubwugrwwrbguwbwbgguwug\n" +
            "gwrbbbwbuuggurwuwgwruwbrrwgrrugggrbwgbwrrbgwgbwgwrrruur\n" +
            "wrubuugugwbgubwggbbwuuguuguuuuuuuguggrbrrwubuwrgbrbu\n" +
            "wruubbwrggurwwrrwgrbrbbbwrrwbgggrbgguwrwwwwwrguwubr\n" +
            "grbgrgwgwuruubwgwuwgruubgbgggbuuubgbuubgwrwwruu\n" +
            "wwwuwuurrburgrbbrgruurrgwwbgwgrgbrggbgbgrrwbr\n" +
            "ubrbgbggubgbruwbgrbuugggruurubrurggbrbwwwwwbgguggrggb\n" +
            "guwbwwubbrgurugurbgbubbrgwrugbbgrbbbbwrwbwubrwwggrurbuu\n" +
            "bubburbwgbwbbwuguubbbubbwbbbbgrrwbwgrwggrbggrrrgbw\n" +
            "uwbwruguwbrrrrbgggbbgwgwwbbuuguwbuwuurwwgbrwbrrgwwgguwwwu\n" +
            "wrwwguwubwbbgwugwrwgubbwuwwwbrwrwgrbbwrbwuur\n" +
            "bwbuuwbwuuwwrwuwubwgbwrguwgubuuwbrrurrbugbrruubbuuwrrgwwg\n" +
            "wwbgrgwguubrugugbbubrrrgbbuburrguurggrrwrbbrrgbuuugbbrbr\n" +
            "bwuugwwbbgurwurugbguuubrwrwrgbwbgrwrbwrruwgwg\n" +
            "rbgggwgrgrbbggrrwbuwwrwwwwuuwgwwbgbwbubgbbwugburwugu\n" +
            "ubrggwwbrgrwrwbwwwbggwrgurugwrwrrubbwguruurbgu\n" +
            "gwurruuggubgrwrbbwrgbbuwbgbugwwgbrwuuwrgrbrbbwrrguwurw\n" +
            "wgubugrrbuwbbwuguwggrurgwwwruuuurrgbuwwbrgbggrgwbuwuwwrr\n" +
            "wrgguwwwrrgrbggbggbwgwgbbwguugbbuwubbwuggrbuwgrbrrbgbg\n" +
            "grrbubuwubrurburwbuggrwbrggwgugrgwuuwbbwubrbwrrwuur\n" +
            "rgrrwwuguuuwgurrgwbggwbgrrwgwwggwuwwurbrbwgugr\n" +
            "gbgurubrubrbwugugbwbbguwruwrgwgwugbgbrgwbbgwuguw\n" +
            "ruuwrubrgbggwbrrwubrwgrwgwrbgrwuguuwwwgrwugguuugw\n" +
            "rubwbbbrgruwwubuwbubrgbrbwuugbuuwurgwurgwugbugbwrgwgbgwgu\n" +
            "gwwrgrbuwgbrgwgggurgugggrwrbggbgwuuubburgurbwbrrwww\n" +
            "rwwuwurgrwrbwbugwbuwgrwwwgwwbrrbwbrruugburbub\n" +
            "wgrurwwrbbubbrbuwruwrubbwububuugrwwwuurggrrbwbbwub\n" +
            "urwrbwurrgbbrbrgrbbuuuwwubrbrbwubwgubwgbbbrbuurgubgbwgbbur\n" +
            "rrwwuwggrruuugbrwwugruwuugwbwuugrwwgwubrrubwgugwwrguugug\n" +
            "rguggrgbwwbugugbgubuggwuwrwgggruwurrgbruubrwggbwbbbuwuur\n" +
            "rwwwbrurggwguwuwwuwwgbbgwrrwgwrburuwuggwggbrrwg\n" +
            "uwwruwbubgrwugggrgrubbrrwuuggubrbbggguur\n" +
            "wrwrwbbbrbbgwguugbbuwuuurgwgbuwwbuubgbubuwbuurubbguwuguwuur\n" +
            "wgbrbbuururgwrwububwbrbrrbwbguwrruwgbbwwwugrbbrwurgbrg\n" +
            "brwwuwuwubgugrbgwubrugrwwburbggwuwwbwrgguruur\n" +
            "ugruburgwwgwguugbbbuwgubguuwuubrgrwurrgbggbu\n" +
            "ugubuubrrwrrrwrbwwgrguurgguruguwggbuwrwuwrgw\n" +
            "gggrwbruruugbgruwbrrubgwrgrgugrbubbuugwbbbguw\n" +
            "gbubbgubuubggguwgggbggwurbgguggwugrubbwwrburrgbruwgugr\n" +
            "bububbuuubgurggrbguuurggubwrrrrwrwuwbggurgwuruwgww\n" +
            "wuuggruuwgurugggugubbrwwggwwburuwwbbrbubgg\n" +
            "rwggwgbbgggrruwwwgwruggurgwwugwbgbbwwuububgbuub\n" +
            "wwbgwbubgbwburrwggggbwugbbrubrrrwgrwuwwbwrbggwwgg\n" +
            "ugwgrwrwwgbgburbgrrwrurgguguuburgbruwgbwurwbrggbwu\n" +
            "gurbrbrrruwrurrubrgurgbugrruggbuwuburrrbbbwwubgbgww\n" +
            "wuuggubbwwwbbggbgrrbwgrrrbuggrwbrgbrurrwbrurbgwb\n" +
            "rbggrgrwrurwbwwrgwgbugburbbwbwwggbgrurwgwbggguuurguwr\n" +
            "wwrgugrubgbuwguwrwwuwrrbgguwgrwwubbbbrubgbrugubrrwrrbgwurg\n" +
            "rrrguugrwbbuwgurgbwbbgguurggruwgggwgrubrbwwb\n" +
            "bbuuuguwrwuwbgbrgggrwuwgugwrwuwgrwrrrrurubrwurgrbrbwbrbwgg\n" +
            "gurwruwurwgguwbggbugbggguwwrbruuuggrbrbwubrugrbggurwwbggruur\n" +
            "bbwgwgrbgwuugwbrrgwbgwguggrbrrbwurubgurgrug\n" +
            "gwwrgrbbwuwuggrurrbbgurwguwrruwwgwbwruurrwuur\n" +
            "ubrgwwuugurgbgbrwugubbrgrwurrbrgugwrrurgwuwubrruu\n" +
            "ubggrwrgrrwgrwgbrwwggrwurbgrurwugubggugbwuguur\n" +
            "bgrruguuwrwwuugwuwbwwwbwwruuwrwbbubrruur\n" +
            "bwgbwbwugguwuugwrbrbgwrggwwgrurguuwbgbbwubguubwuuw\n" +
            "bgrgrrrwbgggbwgrruwgwwgrrrgbbubrbbwrgruurrw\n" +
            "gubbwrwuwurwguugugugggrubrgurgguugbgrrugwbrgu\n" +
            "grgbururuwubbgugubwgbgggrgrwrwbbbrguwggrbugbgrw\n" +
            "guugwubwbbrgggrggrwbwuruwguugwwrwbwubgwbub\n" +
            "urguuuwgbwgwggbrwugguuggugugbbuwgwgbbrbggur\n" +
            "ugugggbubwwwuggwgbbrrwbbbbrrbuwgwrbwrggurwggwwg\n" +
            "rwwgwgrugubwwgbuwgwuuwburwggbbwuuwrrguuugrwrububrwrwgubwg\n" +
            "wguuwbbggwubbguwubwbrrbuuwrrgbrrwbgrwrbgbubuwuur\n" +
            "gggugrggbrwwwwbrgwwwurgugububgrwwugbgrwrwruwwgrr\n" +
            "gwugruugrwggguguwuubbgbbubbbggwwuggburbwuggwuubbbwwrwgwuur\n" +
            "rurgwgrwgrgbrrwwwrgbwbwrruwguuwgrburbbuuwwwru\n" +
            "grgurgggruubbgrbubbwrgrggbgubuugwgurububgwrugggwggugbbruur\n" +
            "urgrugbwwrrrgbgurggugrrubuuuuwrrrrwwwuwugbruuggwgwuwbbbww\n" +
            "gguwgruuurwugubrgbrbwgugrurrgwuwrubgrwggbwgggu\n" +
            "guwbubguguurgruuguuurubrbwwwgbuwugbbbuwgbbbuwubwwwggg\n" +
            "gbgbgguuwbwbwubwgrbwuugrwuwrrbgwrbguwggbgwbbwwuguwguruur\n" +
            "rgubbwgrggwwwgbbwgbrrggbgwrrbgbgrbbburbgbbrwuurrgbruur\n" +
            "wgbwguurruuuburbbuwbbrwwrugbwwwuwgrwrggbubbw\n" +
            "uubuuurwgbgbrbbgwruuwbuwrubwuguuurwrgbwbrbwuwbubbr\n" +
            "uwrurrurrrwwwrrrbubwuuuggrbruwwwrbbbwruguugrwrgwuur\n" +
            "bbrwgbbrrwrgwwrbwbwuggbguuguwrggbruuwurrwggrr\n" +
            "ggburrgbgurrgwrgbbwguwbwugbgururbubrwwwubrgbwuuggrwbu\n" +
            "rgbgubuwbbguwuurrrurgrwgrbwwbbrubrbbgwrbgubbrwrrb\n" +
            "gbuwburgburgwgbubrugugwuwgbbugrwrbugwgrubwrb\n" +
            "wuubrbgruwubwguuwwrburbgwwwrbbrrbbbwbwbggrgbbuwwrgrrwrruur\n" +
            "grgurwwbbuububrrrbrgrbruuuwuurggwrburrbuwugwrrgruruur\n" +
            "uwguurgrrurgwrurgwuwugbgwugbbbrurrbwgugbbubwwrrr\n" +
            "rrrgrrwbrwbwwgurruwrgrwwwbbwbgbuwrurrggbggwbuwurguggb\n" +
            "bruwwugwbgburgbruuwbwwwuuwrbbbwrruuuwggrwugruguur\n" +
            "gbwbbrrubgurbgruuubwwwbwgubrrruubwgwugururgguugrwrrwrwuubu\n" +
            "bbggbuuuwugwwuugburgugwbgrwrurrurruwgrwrwuwbugbg\n" +
            "urgubrggwrwubwwgbgwubwwgwbrrgbugwrgbgwuwbb\n" +
            "gguggururbuugrwbgrbrwrrbuurgwwrwgrbbwwgwwrrbrrgg\n" +
            "uurbbbruwrrggrgwgrbgwbrwubgbbgrurrgrgrgrwr\n" +
            "ugwbuubbwbwrwgrwburrrggbrbuwwrwwrwbrrwurrgwwwuwwb\n" +
            "bgurbuurbbwbwurubrwurggwgruwurgwgrwuuwbwuwwbrgwrr\n" +
            "brwrbwgbubbwgggbwrrwwgurgggggubrrubbbbrugggrgwuu\n" +
            "rbruwggbggurbguwbggrburrbbrrbwrrguwgrrburbuug\n" +
            "ggwwubbwbgbbuwrwugrwubgwgwrrwbugrubuugrrrruubwub\n" +
            "gbbguwwrwuubgrrggrubbuwrwrwgurbrwbggwbgugr\n" +
            "gwgwugbrbbubgwwbuggwwrrwwgrrgwwurbuuubwguuw\n" +
            "wgrrbugrwwwwrurbrwwuuggwguwwgrbwwubwgububr\n" +
            "uwwgugburwrwuwuuwrwgbwwwwuwwgwgwrugrrrubrbg\n" +
            "grruwruwwbrugrruggrwwgwwbgbbuguwuwwuguggwurwuugguur\n" +
            "gguuuggbuwgwuuubbwbgbuurgwbrbgguwgubrrguuggwbggwwuur\n" +
            "burgggbgbbbgubbwuubgggbuwguugubruwuuggwuur\n" +
            "gugbbbubuwbgrrrrrbgbgwwwrbgwrbgbgrrgwubuurwbgwr\n" +
            "ggrwgbburrrubguruwrguguwbuwugugrguwggbrugrbuuwwbggbwwubr\n" +
            "wuggbrrggrwbgbgrggrburuuwrwgrggruwggbgruuurrguubwwgubugbw\n" +
            "gwuwbwbwubwbugggugubwgwwrwubwrbbwrubrgwwuubbwggwg\n" +
            "wbbguuwrbgwwuwurruuwburwgbwubwgbbuugurugrwugbugu\n" +
            "uwwuugwuwuwguubbbbbuurrrubwgrbbruwrwuurwrbruguggwuwu\n" +
            "wwuwbrrwbbrrwgrgwrubruwbuuubugrubbuwuwrruwgrwrww\n" +
            "rrgbuuwgwbbbgbuuuwwwggwrrbgbrgwbuurgbwbbwbbwwugguu\n" +
            "ubbwgwurwwurrwbbbwubwwbgwwrwrgrubwbrgruwugbwrwbwgwbuw\n" +
            "rruuwgrwwugrwgwbuwwbruuuggrwrgubbwgwuubrgbrb\n" +
            "buuuguubgwbuggubwggrbwgguwbgugbuururbbgbwbrwbrrgrrwgrurwgu\n" +
            "gbwwwwwggrrbuugugbwwrubbrrgggrubwuubgggrgugubbbrwb\n" +
            "bbgwgwubwrrrrwrrrgruwrugwrbbuwrgruuuwrgwbuwwbrguuuwubw\n" +
            "wgrwgrwbbwrrrbuwwrwuubrbbgrrububbwrwwwbgurrrwugwubgrguuwuur\n" +
            "rrwubbuububwrrbgrbruguwgggwubgugwwggwbubbrguruurwgbuggrwg\n" +
            "wubuwgrrwgwgbwgwugurbruwrwgwgbggurwguwuur\n" +
            "rwururrbrrrwgwwubbruwbwwrgururbgguuguuuwwrbwrgg\n" +
            "ugwuuruwbwgurbggurrrwrgurgurbbwbbuurbwgwwbbugubgub\n" +
            "rgwwubgrbwbgwwbwgburuuwurugguwuugbwguuuwug\n" +
            "grwububburuwgugbgubbwwgugwrwwuwwwgwurgrurgwwrbwg\n" +
            "rgurbwrbrbubbwbwuurwrwubwwgurrwbwrbrwgwrwrrbbbb\n" +
            "wwgwuguuwubbwrrugubugrbwbubwuwbbbbrgwrrbrwuwbwbb\n" +
            "buubgbbbwbgrwruugurggugwubrrrrbbubbwwuguwruwwub\n" +
            "wrwbwuubbubwbuwrbwgwububgbbbruwuuuwuubbwrbrrwgrbuubuwbwu\n" +
            "wugwwbrrrgbrbgbwgbuuwwuggurbwrbgwwbbgwwgbbu\n" +
            "rgrrwugbgbbgbrwgbrrbuwwrbbuwruurbrbwbbwbururrgbwuruu\n" +
            "bubugurbbgugwuubuurrwrwubrbuuwrrwrbrwwuuurrwbww\n" +
            "ugrwubwwrgrrbrgbgrbwbbrgururrrruugububwwwwwbgwwugb\n" +
            "ruurrrwbbgbbburgbrrrrwuuwwuwbggbrgwbuwwbrbbgbbugwwuur\n" +
            "wgubgrgguwugwwggwbwuwurugugwgwubrrrwggwuubuubgg\n" +
            "uwrrruuwrwggrgrrgrruwruuwggrugwrguguuguuwuugb\n" +
            "wgrbrruugwrbgbwbrbgurgbbugggbbgwuubbgwbuguwwuuwbgub\n" +
            "ugggruggrwrrubggbrbubwurwwubbuwwbwugrrbwruwwubbuuwgbuu\n" +
            "uruwrwburwruwwbburrgrggbugbggbbuubwbbggbbbggbgggwr\n" +
            "uuuuwgrwurugbgubrwgbgbbugwwuwrburrubgurrwrrbbrguugugbggguur\n" +
            "grurrwwwugbuubgugwrwguubgbwwgggbgurwguur\n" +
            "rguwwrgrwgwrbrbwggbwuuuuuuurwgguurbuwrwbrwrwbrgbguuwuu\n" +
            "rubwbburgbrggbgwwrwbbguuggbgubrwbbrgwgwwuuugruwrrgr\n" +
            "urrrbubrggubwwwubrwgwuuwurubugurwgbguugguwbwrrwwwurgugr\n" +
            "uuguwuwrbrrggwubwuguuwgbbwbrbggrwrurwubuwbgwubrb\n" +
            "bubbgwugwgwbbwwuwbwgrguwrguwrbwguwruuwwrbwwgg\n" +
            "grgubwbrrgrrbbwgwuubuwugrggwrgwururwuuguur\n" +
            "rrwubbwwwrubwrgugrgurgbbbwuwuggrbuwuwgbrwrbrbrwurubb\n" +
            "ubrwwgbuwwbgbugugbbbbrbbwbrrwwurrgbrurbuuwgrubbgurwru\n" +
            "urwbwwburrruurwrwuggubruubbwrwrgrrguguuuuwrbwg\n" +
            "guuwugwbuuuggrrrbgwuwrggurggbubwwbgugbrwgrbguuuwuur\n" +
            "bwbrrgrwbwrrguubrbuwurubbgwgrggbwggbbuwgwrguugu\n" +
            "gurruugurgwgbggwgbgrbgwwgwubwgbbuburgurwrggrwrrwbbuw\n" +
            "bbgrrbwwbrgbgugrburrgubgubrbwuwuwwwwwrbubuubgbbbgwbrgg\n" +
            "uwbwrwwuwguuwwggbubbgrrugugubgggbrbggrbwgwuggubu\n" +
            "gbbwrwrrbwugwgrubbbbrrbururwugguuuwbugubbbwwbgbbwubwwbbuw\n" +
            "ggwbbgwgwwggruurruwugggbrguwubrurwubuwbrbuwrgrrr\n" +
            "rubrrurwbrwurguwbrrruubuuruwbrbbbwuuubrbbwbgbgwrwggurbgr\n" +
            "rgwgrwbwrburwrbgururgbwggbgurbbgrurbuwubbrrrgrrbruuu\n" +
            "buwbruwbuwrggwbwuwuwbbuwbbbubbwbgrwbruwwuururgbur\n" +
            "bwgbrbugbgguurwuggggugbggguwwrbwbbgrrguuwuuwrbrbb\n" +
            "wrwuuwgwrgwugbbrbgbwgubbwwrugrguwuurwbbuugburrbur\n" +
            "guuugugubwgwgwuugwgugwrgbruuubbubbbgugwwrur\n" +
            "rwguuubbuwbrubwrwwuurrbgrgubuuurrwubrgwrwrg\n" +
            "rgbuuuggwrbgbwrububwurubbuugubwggbrrwrgbbuubwwuurbubwr\n" +
            "wwggwwwuwurwbrbrbbbwbwggrbgubbuwggbbugrwrrrgbg\n" +
            "gurrugwurbuwurbrwbbbbwugrbwrguwugwugrbrgbgbgwgruguur\n" +
            "wbwwwwrbgwuwubwrggbuggwbrwrugbgrgrguwuggwggwbgwuwgbruwugruur\n" +
            "wubrbwurwwbrwggggugbbgrrrgrwguggurbbrugrwbwuwrruur\n" +
            "ggruwgugruuggbwuugrwwwgrwuugbugwwurwrwrwgggwbuguuwrww\n" +
            "wrrrrugbbbwggrgbwrrwrrwbgwrugugugurrrbggwugbbgbw\n" +
            "rggwgbuggruurwwwruburwuwrbrubgguwubgbubruuubuurwgwugubwwu\n" +
            "ugbguwrggbruuugwrrwgbgugwbwuwbbrggwurbruuu\n" +
            "urguwuruubgbwgbguwgwubugugurwwrbggugrbgrubwrbgbbbb\n" +
            "uruubbburbrwwwwrruwrwgrrwrwgwurrbrbgrrbbbruur\n" +
            "uggrugguwbgbrwbrbwbubburwwwrbbwuwwubwbbbwwbrw\n" +
            "rubrgugubbwuubbbwgrrbwwgwggguwwrbburggwrurwrgrru\n" +
            "ubuwrbgubbbwrurbuugwuwwuwugbggugbbbwururrurbbbbrubbbrwu\n" +
            "ubgrrwggruurggggwubgrgggwgugurrwgbgurgrrubuwgwugruubu\n" +
            "gbrbbrrbuggwwgwwbrbrbruwugrwbbrgrbwgwbgwrw\n" +
            "wrrwggburbuwururbbwgbwuwgbuggubwwgubbrubbbgbbguur\n" +
            "guurwrggbwruubrgbgbuuurwugruwbugwggbgwbbgg\n" +
            "wugugwrbgbrbwwuwugbwuubuggrrrwgubgwrbbubgwg\n" +
            "uuwwugbrrwrubbrgrurwrwwrrwwbuwruwrgugrururrwrgwwbwug\n" +
            "wgrbuwgbrrrgbruwgruuurubbrwguugurugurgwrggbgbur\n" +
            "rgggbggrrbwwbuwggbuwrubbgwwwbbwburrwuggbgwwwwrwubbgr\n" +
            "ruuwbrbggbwbuuwuwwrbwbwbrbbbgwubwwgbbugbugugub\n" +
            "rrurbugbrwuwguwgwbuwbubrruuubbbwwbwbruwbrww\n" +
            "brwgrruuuwwgggbwwbuguruwrgbugubrrwrbbrrggbwwrruwuur\n" +
            "uwrwbuwurwbwbrbrubuuwbuggwwgurrwbrrurggwrgbwgruwbg\n" +
            "ubwwbruwbrubrbggbuugwrugbrbwrggwbwbgbruuggrbbgrwruurwr\n" +
            "uwbwwrgbuwrbwbbbrbwrguwwgbwwwgbguuwugbuwguwugrrrwrbwurw\n" +
            "rwrgugbrbuurbrbwurwwrrrrwggrwugburbbwgrurruwwbgrguwrru\n" +
            "rbbburrwbbrrugwgbuwugwwgwgwrwurugbwgbgbbruwbbbwbbbrgwbr\n" +
            "rrbgwruwgwbrrrwuururrrwbbgugrwbbwbggwgrburgg\n" +
            "wrgubrruwwwgbgwwwgwrrgbbrwbbruurubrbugrggwgurwwrru\n" +
            "ugbrwwwwwgugbugrrbrrruwugbgbgbbrbgrbbwggrgurrbwbbbww\n" +
            "wuurggrgrbbubuwgwwguwwrubrrrgbrwgrwgrwrrwugbgguugbu\n" +
            "uuwuwbrwwgbrrrrrwgwbubrrugbguburrggbgburbbwbbgbbbguw\n" +
            "bgwrgbbwurwubwwgbwuwwrrwwwrwgruuuwbrwwrgbrbgwuuuwrrwgr\n" +
            "brgrugugwwgrrguggbgbwrbbrgbwwbbgwuwgwgrrubrgwugbbgwgrruur\n" +
            "gwwgwruwwrubbuwguwrrgwbubugguuwggrbwgbgbrurugbwuruur\n" +
            "ggwwuwwgrwbrbrbuggrgurrbububwrwrurrruubguur\n" +
            "bwggrbrbbuwugwbguggrbwbrbwrgubrubwbuwggugbr\n" +
            "wgwuwruuuuugbwgwbbruugurgbbwbguubwwuwugwubw\n" +
            "rwwrbwwrruwburwrruwbwugbbrrrburrruurrwgubuggwg\n" +
            "buruuwwwguubbuwbuuruuwwwrwugwubwbgrwrbwbbrgbrr\n" +
            "rbrurbgwwrgggrbbrwgwrugwwwrwgwrurbburguwbgrggbbguur\n" +
            "rugburuubugggrwuugrrbgbguwrbugruwbbwwrurwgrgwgrwuur\n" +
            "gwruggggrgbgbwbrgbgbgbwbugwbuwbrurbbbwwuur\n" +
            "ruwbrrbrbrwuguwguggggbgwwbwgrbbubrbwgugrbgruwuwwuruuwu\n" +
            "wuguwwwguugbwwggggwbubububgrwrurwbgrwuwgurrbbrrbuggwbbbgruur\n" +
            "guurgbrgurbrbugbwgbgbubgbbgwwwgbrgwrrbbgrgrubbb\n" +
            "grurwbrwuggrbruwwbbruwurbbrwwbrwbuurguggwwbruggrbwbrwrb\n" +
            "wwwububuwuggwwrrgrbwubbgwgubugrwugwburbgugwugbgugwggugrgb\n" +
            "bwggbrrwrbwrwuugubuugwgbwbbbugrururwbwwbrwgwwurbuuwguwwuur\n" +
            "bgruwrruwrurbrbgbgurggbubwbbwgbwrrwurrbrubbbbuwwgrwwbbu\n" +
            "ubwrbrrwguruggwguwbgwbgbubgguggrgwwwwbwrrburbbwgwr\n" +
            "rrrwgrgwbgugwrurwbrrubbuwrggbruguuurggbgwwbwgbwuwgwrrwuw\n" +
            "grrgwgwrurrgbgggwurugugwggrgwwbrubrgbrguur\n" +
            "ggugrwbbgbuwwguuwgbrbgrgbwbbwruurggrgwwgwuubrguubgubguur\n" +
            "urgguwggbbrggbuwuggwuuurrbbgurwuubwwubbbbguwbwgwrwuuugurgg\n" +
            "gwubwwgrrbwwwugbrbwgwugrgrbuurwwbbuurggurggrb\n" +
            "rbugbuwuggubgbrbgrbgrrurbugbrrgubggwuwbwbbwrgubb\n" +
            "rbwruwbgbggurrbubwwbrrwbubuwguuwbuguwbwwubuuwrub\n" +
            "rrwguubwbgwbbrgubbgbrwgbwwrurgwbwwbwubggrrwwgguwrwwubuwb\n" +
            "rbrurgbgbrrgwggrbwbubgurbbbruurrgwbugurbwrrbbbbwwgbw\n" +
            "wugbbbuwrrbwbbggbgwgbwrwgbbubwwwbrruwbbbrbrwb\n" +
            "uwwwbwbbgwubwuwgbbgrrubwwbrguwwrbruuwuuruww\n" +
            "gwubbuuubbubbbubuwwbwuggugbwwgwwrbruwggwuubgwuugguurb\n" +
            "urbwwgbuwubgbwuurgrbwbgwgbbbggbgggwgwbrwrrbrbbgwu\n" +
            "uwuruwwbggrgubwgruwrubrugwurubgrwwguurwrrrrrurbruwgbg\n" +
            "uugguugwbbgurubwbubwrwuwwururwubwwbgbugrbrrrbbuwbgbwgug\n" +
            "wrwrwwgguwggwbguubgbwrgbguggwuwubgrubwubbrgrwbbubrbuwbw\n" +
            "bbgrwrbbrggwwbbubugwwruuuurwgbrrugwurggbgrbwbrruwuur\n" +
            "rwwuwurbbbwgrurwwububwrruwbrubwrbwrwbuwgrbggbuubur\n" +
            "urggbrrrubrwbubwgbgbbgrwggrgrrgwuuwwwwgrrru\n" +
            "urguuwrruuwrugbbrbuwgbgwgurbwuwgubbgggrwgwrur\n" +
            "wgbbbgubbgbugrbbgrrbwgwuwbwrbwbuwrbuwbwuwrwrugb\n" +
            "rugubbugugugwurbwbwwbubwgrwrbwbbrugrwbwwwrbgwwgguwuwgrrgw\n" +
            "brguwwgbugwwrgbwwggwrwubbbburwuruwrwwrrgrwbrwrurrug\n" +
            "wwbbbugwgwwgurgbguwbwgrbrgrbwwuwwububbgubruur\n" +
            "bgbwgrgbwgugrbgbbbgrwgbbbuguuguwwuugrrwwwgggrgubrwgbrwbu\n" +
            "urbrrggrurbgburrgrgggwuggubwwwwbbgwrgbbbuuuruur\n" +
            "uwwruubbrbbwugrrgrbugbrggbwurugguwggbuwrwrrrgrwgbugbbwuruur\n" +
            "grgbwrgwwuubrwrrbugbrbwrwburubrwggwuwrgugw\n" +
            "rrbwwwgbbruuurwugruwbgrubwbugrbbwgugwgbgbwwub\n" +
            "urgbuugrururrggwuuggugrbbururwuwguuuurrbuurbbgwuwuur\n" +
            "gbrwuuwbguuburrwbrrruurgbrwuurgrguugggwubbrrrbuub\n" +
            "bgubuwwwuururbrbrbruggrugguwwwwbubwrbrbwrbwruuwwbwgwwg\n" +
            "grruwuruwrbrgbwbuuwrurrbubrgrrgrggruwguwubrrgrgbr\n" +
            "bbbgrgbuuugrgrwuubwwwrwubgwgururwbggwubgbrww\n" +
            "rwgwurwrubgrwrgwwuuubbwrgrrrwurwrgbrwwgbbwrgur\n" +
            "rwurgwgurbggbgbggurwrgwuwurrbuubwubggrrrbrrwgw\n" +
            "wuwgururrurgwrwgubrugggbrwguwbwwrwgrwugbbrbbguuwbbrubu\n" +
            "ubgrugguwuugwbrubuuwbbgwgrgrggguwbrgwwwrwuggurwwrgg\n" +
            "wbuwurgurgwbwrrgbbbrggbgbwbguuuwrbgrbgururrgb\n" +
            "brwwuugbuuwrurgwbruwgbbwugwubwrbwbubruur\n" +
            "ggwuurubwgurbbwbbuwuugwbwguwbbguwgbgggggrwrrurgbbgu\n" +
            "rrgrburubuwgwbuwruuwrrwgbwubbgbbggrwgrwuwgrbuwbwbrwuur\n" +
            "ruugggubuurrwbuuuubrbugubburubrurwrgurbwrwubbgrgugwgbru\n" +
            "wwrbwrgguubguububbgbbbbrrbbwrbwwbgbrggbrbgbwgbwrurguuwbr\n" +
            "bubrgrwrwurubbbgwrbrurbgbgbuwubgrubwwbggrwbw\n" +
            "ruubbbwbbuguwrrwwbwgbrwbggwbuwbbugburuwwbgbugbbwgbr\n" +
            "rwrrwwrbrgruuwwwwrggurwwgbrbrbrurgruugwwuwru\n" +
            "wrgurrggrrgbbgubgruugurggbrwbgrguruwbrgruwrguwr\n" +
            "wgwwggbwbbrurwwgwubugbuggrbwwgugbbrbrwgugbgugrg\n" +
            "gwrgrwurgbguugwrrwurbbrgubbwbgrubbwggwgwbuwbuwuguwwbbw\n" +
            "bgrbbggbgwbwwruwubuwrgguwubgbubbuwrwwuuwrrgwuwrbggbw\n" +
            "wbwwbwrrbbbubwwuuuurrgubuuwwgbgrugrbbubwggrbrwrrwwwuwuur\n" +
            "wgurwwwwurrrwuwggrwbrgwbgguwrubrrggwrwgbbrbbbgwwbrgrbrgrr\n" +
            "wuwwwuuuubbwrbgwgrggrggbrgggbbuwubgugbbuburrgrggwrguwgb\n" +
            "rgguggrbggbwrwbrubrwgubrwruwrwrbwggububruugubrrruuwbgu\n" +
            "gwuwwururruwgwbbgubgwuugbuwuuwwgwgugrbwguggbugwwbr\n" +
            "rbbgwgwggbrguuuugburbuwgwbrrwugrbbggbrgrwwb\n" +
            "gwrubwwwbruruuwgwgbwbbgrbrbrwwgruugbgbugbggwbbwgruur\n" +
            "bggrgwurbwwrggwgrgrgwuuuwwruggrgrrrbruuguwrgrwuuwgguur\n" +
            "uruuubgbbrugubwrgbrbuwgrwwbwruggguugurwubrrwu\n" +
            "grwwuwuwgguuwuggwrrwwwrrwbgbrrwrwubbuurrrbrbb\n" +
            "uurggwwgrgrbrwubgrwgubgbwbwurbbuuwwuwgbgrgu\n" +
            "ggrbgbrgrubwuwrguwbguuwrrgwgbwbbgwwgrgururwggbwbugwbuwuwu\n" +
            "bubgwruuwbbbruwbrrbbubugwbwwubgrrwrguuwuubrbrbrg\n" +
            "wurbwguuruwwbwrrguwrguwgguwrguwbubugwggguwwguugubbruuugb\n" +
            "bwwbuubbrbwgbuwrbruurrugbuuggbwrrbuwgwuwgwgurbbbwuur\n" +
            "bgurgwwgbbwbuurrwbwrggrgwrbrubbuggwruwbubugbggrrwgburgbwgr\n" +
            "wwwwwwrgrwggwgwwgwuwgurwbwbwgrrruwrguugwburgbruruuwwuur\n" +
            "uguwgggbwbgwbwuwrgguubbwgububbbguwgbgrwrgurbrruur\n" +
            "bbuubrwwugburbruurrwbrbwgwbubwwggbuwwwgbgbrguuwbrrwrg\n" +
            "wrrwbbwrwwbwrwwbwbbuuubwwbwbwbuurrwbbbwwrgwwbbrgwuuwgwgw\n" +
            "rggrwwgrburgbbruuuggbgrbrbgwbrwuwgbbgwbbrwgg\n" +
            "urwrrubrgrurbrrwwuwguuwbwrrrrrruwuwubguur\n" +
            "rbwrwrwrgwrwuwwrgrbrwwrbuggbugwguwggrwggrrwruur\n" +
            "bbbrbbrrwubwugwwwruruwruuuwruggrrgggbruuwgbgruwuwuwgu\n" +
            "rburbgubuguwbwwrbwruwburbwgurgwgwbwbbgbugbugwubuugrggwbgrw\n" +
            "brubwbugugwbwbuwrbbrgwwubuwbuurwrgburrgbwbwuwbwbbrgwrgrwg\n" +
            "rwuurggubrrububugggrbuwbbbwbwuuwruggubbwuur\n" +
            "rrbrwugrgbuggggrggwbwuuwrwruubguurwburgbbgrguwbrugbwruuwuur\n" +
            "rubwgbgruruuwwubgbugrggwrwbbwggwgbggbbbbwgrgbbuwwruwwu\n" +
            "urwbwrrgggwwbwwubbubuwubuugwuwrwggwuwubwbwguw\n" +
            "wgbrubbrubrwgwguuwrwgwwuwguurrwbggrwrwwgbuwwurwrwubrg\n" +
            "gwubbuwguububgruwwwwbuurwgwgugububguwgbbbrrwurwguurgburb\n" +
            "bgurburuuggbruwrgrbbwwwwgwugguwburbbrrugbbbwrrbuwugugrbg\n" +
            "uubbrrbuguuwugbwwuwgrbbbggbrwgwrgrwugggbrubuggrwrbgb\n" +
            "gwbggurrgbwgrugwuburwbrwuruwguguruggggbugwww\n" +
            "bgbwrrurubwgrubrrgggggwugubuubrgwrrwwwrwwuwww";

}
