public class Day12TestData {

    public static String inputExample1 = "AAAA\n" +
            "BBCD\n" +
            "BBCC\n" +
            "EEEC";


    public static String inputEXample2 = "OOOOO\n" +
            "OXOXO\n" +
            "OOOOO\n" +
            "OXOXO\n" +
            "OOOOO";

    public static String inputExample3 = "RRRRIICCFF\n" +
            "RRRRIICCCF\n" +
            "VVRRRCCFFF\n" +
            "VVRCCCJFFF\n" +
            "VVVVCJJCFE\n" +
            "VVIVCCJJEE\n" +
            "VVIIICJJEE\n" +
            "MIIIIIJJEE\n" +
            "MIIISIJEEE\n" +
            "MMMISSJEEE";

    public static String inputData = "IIIIIIIXXXXXXXXXXXXXCCCCCCCCCCCCCCCCCCXXXXXXXQQYYYYYYYYYFFFFFFFFFFFSSSSSUUUOOUUUUUUUUMJJJJMMMGGGGGGGGGGQQQQYYYYYYYYYYYYYYYNQQQQNNNNNNNNNNNNN\n" +
            "IIIKIIXXXXXXXXXXXXXXCCCCCCCCCCCCCCCCCXXXXXXXXXXYYYYYYYYYYYFFFFFFFFFSSSUUUUUOOUUUUUUUUMJJJJJMMGGGGGGGGGGGGQQQQYYYYYYYYYXYYYNNNNNNNNNNNNZNZZNN\n" +
            "IIKKIIXXXXXXXXXXXXXXKKCCCCCCCCCCCCCXXXXXXXXXXXXYYYYYYYYYYYKKFFFKFFFSSUUUUUUUOUUUUUUUUUJJJJJJMGGGGGGGGGGGGQQQQQYYYYYYYYYYYYNNNNNNNNNNZZZZZZZZ\n" +
            "IIKKIIIIXXXXXXXXXXXKKKCCCCCCCCCCCCCCXXXXXXXXXXXXYYYYYYYYYYKKKKKKKKFFSUUUUUUUOUCUUUUUUUJJJJJJGGGGGGGGGGGQGGQQQYYYYYYYYYYYYNNNNNNNNNZZZZZZZZZZ\n" +
            "KKKKKKIIXXXXXIXXKXXKKKCCCCCCCCCCCCCXXXXXXXXXXXXXXYYYYYYKKKKKKKKKFKFFFFUUUUUUUUCUUUUUUUJJJJJJBBGGGGGGGGGQQQQQYYYYYYYYYYYYYYNNNNNNVNZZZZZZZZZZ\n" +
            "KKKKKKKKKXXXXXXXXXKKKKCCCBCCCCCCXXXXXXXXXXXXXXXXYYYYYYYKKKKKKKKKFFFFFUUUUUUUUUCUUUUUUUJJJJJJBHGGGGGGGGGGQQQQYYYYYYYYYYYYYNNNNNNZZZZZZZZZZZZZ\n" +
            "KKKKKKKKKKKXXXXXXKKKKKCCCBBBCCCCCCXXXXXXXXXXXXXYYYYYYYYYYOKKKKKKFFFFUUUUUUUUUCCCCCCNNUJJOJHTHHHGGGGGGGGQQQQQYQYYYYYYYYYWYYYYNNNNZZZZZZZZZZZZ\n" +
            "KKKKKKKKKKKQQXXXKKKKKKCCBBBBCCCCCCXXXCXXXXXXXXXYYYYYYYYYYKKKKKKKFKKFFUUUUUCCCCCCCCCNNNJOOHHHHHHHGGGGGGGAAQQQQQQQYYYYAYYWWYNNNNNNNDDZZZZZZZZZ\n" +
            "KKKKKKKKKKKQXXXXKKKKKBBBBBBBBBBCCCCXXCXXXXXXXXXYYYYYYYYYYKKKKKKKKKKFFFUUUUCCCCCCCCCNNNHHHHHHHHHGGGGGGGGGAQQQAAQQYHHLYYHWWYDNNNNDDDDZZZZZZZZZ\n" +
            "KKKKKKKKKQQQQQXXKKKKKBBBBBBBBBBCCCCXCCCXXXXXCXXCYYYYYYYYYKKKKKKKKKKFKKQQUCCCCCCCCCCNNNHHHHHHHHHHGGGGGGGAAAAAAAAAYHHHHHHHWWDDNNNNDDZZZZZZZZZZ\n" +
            "KKKKKKKKKKSQQQKKKKKKBBBBBBBBBBBCCCCCCXXXXXXCCCCCCCYYYYYYYKKKKKKKKKKKKKQQQCCCCCCCCCCWWNNHHHHHHHYHGGJJGGGAAAAAAAAMMMHHHHHHWDDDDDDDDDDZZZZZZZZZ\n" +
            "KKKKKKJKKKSSKKKKKKKKBBBBBBBBBBBCCCCCXXXXXXXCCCCCCYYYCYYKKKKKKKKKKKKKKKQCCCCCCCCCCCWWWWHHHHHHHHHHHJJJAGAAAAAAAAAMMMMHHHHHHDDDDDDDDDDDZZZZZZZZ\n" +
            "KKKKKKJKKSSSEEKKKKKKKBBBBBBBBBCCCCCCCXXXCCXCCCCCCCCYCCYBKKKKKKKKKKKKKKKLLCLLEECCCWWWWWWHHHHHHHHHHHHHAAAAAAAAAAAAAHHHHHHHHHDPDDDDDDDZZZZZZZZZ\n" +
            "KKKKKKJJKSSEEKKKKKKBBBBBBBBBBBCCCCCCCCCXCCCCCCCCCCCCCCCCKUUKKKKKKKKKKKKLLLLLEECCEWWWWWWHHHHHHHHHHHHAAAAAAAAAAAAAAAHHHHHHHHHPPDDDDDDZZZZZZZBB\n" +
            "KKKKKJJJJSSSJJNKKBBBBBBIBBBUUUUUCCCCCCCCCCCCCCCCCCCCCCCUUUKKNNNKKKKRFKKLLLLEEEECEWWWWWWHHHHHHHHHHAAAAAAAAAAAAAAAAHHHHHHHHHHHDDDPDDDDZZZBBBBB\n" +
            "KKKKJJJJJSSSJJNNKKKBBBIIIIXXXUUYUUCCCCCCCCCCCACCCCCPCCCUUUUNNNNNKKKRRRLLEEEEEEEEEEWWWWWWHHHHHHHHAAAAMAAAAAAAAAAAAAAHHHHHHHHSDDPPDDDDZZZBBBBB\n" +
            "KKKJJJJJJSSSJJJNNKMBBBBBJXXXXUUYUUCCCCCCCCCCCCCCMCCCYYYYUUNNNNNNRRRRLLLLLEEEEEEEEWWWWWWWWWHHHHHAAAAMMMMMAAAMAAAAAAAHHHHHPPHSPPPPDDDDZZBBBBBB\n" +
            "KKBBBBJJJSSSJJJJJKBBBBBKJUUUUUUUUUUUCCUCCCCCCHHHHZZZYYYYYUNNNNNNNRRRLLLLEEEEEEEEEEWWWWWWWWHHHHRRAAAMMMMMMMMMMMAAAAAHHHHHPPPSSPPPDPDDZZBBBBBB\n" +
            "BBBBBBJJJJSSJJJJJQBQBCJKJUUUUUUUUUUUUUUUCCCCCHCHHHHYYYYYYUNYYNLRRRRLLLEEEEEEEEEEEEWWWWWWWWWWWHHRRAAMMMMMMMMMMMQQQQAHHHHPPPPPPPPPPPDBVVBBBBBB\n" +
            "BBBBBBJJJJSSJJJJJQQQJJJJJJUUUUUUUUUUUUUUCCCHHHHHHHHHHYYYYYNYYLLLRRLLLKKKKEEEEEEEEWWWWWWWWWWWWWWRRAMMMMMMMMMMMMQQQQQQHHPPPPPPPPPPPUBBBBBBBBBB\n" +
            "BBBBBJJJJJJJJJJJJQJJJJJJJJJJUUUUUUUUUCCCCCCCHHHHHHHHYYYYYYYYLLLLLLLLLKKKKKKKEEEEEEEEEEWWWWWWWWWRRRMMMMMMMMMMMMQQQQQQKRPPPPPPPPPUUUBBBBBBBBBB\n" +
            "BBBBJJJJJJJJJJJJJJAJJJJJJJJJUUUUUUUUUUCCCCHCCHHHHHYYYYYYYYYYLLLLLLLLKKKKKKKKEEEEEEEEEEWWWWWWWTMRRMMMMMMMMMMMMGOOQQQKKKPPPPPPPPPUUUBBBBBBBBBB\n" +
            "YYBBBJJJJJJJJJJJJAAJJJJJJJUUUUUUUUUUUCCCCHHHHHHHHHYYYYYYYYYYYLLLLLLLKKKKKKKKKKKEEEEEEEWWWWWWWTMMMMMMMMMMMMMMMOOOQQKKKPPPPPPPPPPUUUBBBBBBBBBB\n" +
            "YYYYJJJJJJJJJJJJFLAAJJJJJJUUUUUUUUUUUUCCHHLHHHHHYYYYYYYYYYYYLLLLLLLLKOJJJKKKKKEEEEEEEEWWWWWWWTMMMMMEMMMMMMMMMOOOQKKKKKPPPPPPPPPPPBBBUBBBBBBB\n" +
            "YYYJJJJJJJJJJJJJJLLAJJJJJJJUUUUUUUUUUUUUHHLHHHHHCYYYYYVVVGGGGLLLLLLLKJJJJKKKKKEEEEEEYWWWWWWWWMMMMEEEMMMMMMMOOOOOOWKKKKPOPKKPPPPPPUUUUBBBBBBB\n" +
            "YYYYYJJJJJJJJJLLLLLLPPJJJJUUUWWWWWUUUUHHHHHHHHHHCYYYYXVVVGGGGLLLLLLLLJJJKKKKKSEEEEEEEWLLLWWWWMMMEEEEMMMMMMMOOOOOOWKKKKKPPKKKPPPPPUUUBBBBBBBB\n" +
            "YYYYYYJJJJJJJLLLLLLLLPJJUUUUUUWVWWUUUEEHHHHHHHHHHYHYXXXVVVVVLLLLLLLLLLJJKKKKKKEEEEEELLLLWWWAMMMEEEMEMMMMMMMOOOOOOWKKKKKKKKKKPPJJJUUUBBBBBBBA\n" +
            "YYYYYYLLAJJJJJLLLLLLLLJJJUJJJJWWWWWBUHHHHHHHHHHHHHHHXVVVVVVVVLQQLQQQLJJJKKKKKKEEEEEELLLLLXXAXMMMEKMMMMMMMMMMMOOOKKKKKKKKKKKKKPJJJJJJBBBBBBBB\n" +
            "YYYYYLLLLJLLLLLLLLLLLLJJJJJJJWWWWWWBBHHHHHHHHHHHHHHHHPVVVVVVVQQQQQQQQQEEEEKKEEEEEOLLLLLLLLXXXXXMKKCCMMMMMMMOOOOOKKKKKKKKKKKKKKKKJJJBBBBBBBBB\n" +
            "YYYYYLLLLJLLLLLLLLLLLLJJJJJJJWWWWWWWBBHHHHHHHHHHHHHHDDGVVVVVVVQQQQQQQQEEEEEEEEEEEOOLLLLLLLXXXXXMMKKCCMMMMOOOOOOKKKKKKKKKKKKKKKLKBJBBBBBBBBBB\n" +
            "YYYLLLLLLJLLLLLLLLLLLLLJJJJWWWWWWWWWWBBHHHHHHHHHHHDHDGGVVVVVVVQQQQQQEEEEEEEEEEOOOOOLLLLLLLXMMMMMKKKCCCCMMOOOOOOOOFKKKKKKKKKKKKKKBBBBBBBBBBBF\n" +
            "YYYLLLLLLLLLLLLLLLLLLJJJJJJJWWWWWWWBBBBBHHHHHHHUUHDDDGGGVVVVVQQQQQQQQEEEEEEEEOOOOOOLLLLLLLXXXXZKKKKCCCEEMOOOOOOFFFQKFKKKKKKKKKKKJBBBBBBBBBBF\n" +
            "YYYYLLLLLLLLLLLOLOOOLJJOJJJJJXWWWWWBBBBBHHHHHHHHUHDDDGVVVVVVVVQQQQQQQEEEEEEOOOOOOOOOLOLLLKKKKKKKKKCCCEEEOOOOOOOFFFQFFFKKKKKKKKKJJBBBBBBBBBBF\n" +
            "YYYYYLLLLLLLLLLOOOOOLOOOOJJJXXWWWWBBBBQQHGHHHHHHUHDDDGVVVVVVVVQQQQQQEEEEEEEEXXOOOOOOOOLLGKKKKKKKKKKEEEEEEOEOOFOFFQQFFFFKKKKKKKOZZBBBZBBBBBFF\n" +
            "YYYYYLLLLGLLLGGGGGOOOOOOOOJXXXWOWWBBBQQQQHHHHHHHHHDVVVVVVVVVVVDQQQQQLEEEEEEOOOOOOOOOOLLKKKKKKKKKKKPPPEEEEEEOOFFFFFFFFFFFFFKKKKOOZUZZZZBBBBBB\n" +
            "YYYLLLLGGGGLGGGGGOOOOOOOPXJXXXXXBBBBBBQQQQQHHHHHHHDDVDDDVVDDDDDQQLLQLLLYEEEYOOOOOOOOOUKKKKKKKKKKKKKPPPEEEEOOOFFFFFFFFFFFFMMKMKKOZZZGZBBJJJJJ\n" +
            "YYYLGGLGGGGGGGGGOOOOOOOOOXXXXXXXBBBBBQQQQQQQHHQQDDDDDDDDDDDDDDDLLLLLLLLYYVYYQOOOOOOOOKKKKKKKKKKKLKPPPEEEEEOOOOFTFFFFFFFFFMMMMFKOZZZZZJJJJJJJ\n" +
            "YYYGGGGGGGGGGGGOOOOOOOOXXXXXXXXXXBIIIIIQQQQQHHQQQQQQQDDDDDDDDDDLLLLLLLLYYYYQQOOOOOOOOOOKKKKKKKKKKPPPEEEEEOOOOOOTFFFFFFFFFFMFFFZZZZZZZZJJJJJN\n" +
            "YYYQGGGGGGGGGGOOOOOOOOOXXXXXXXXBBBIIIIQQIIIQQQQQQYQQKKKDDDDDDDDLLLLLLLLYYYYQQOOOOOOOOOOKKKKKKKKKKPPPEEEEEEOOOOFFFFFFFFFFFFFFFZZZZZZZZZJJNJJN\n" +
            "YYYYTTTGGGGGGGOOOOOOOOOOXXXXXXXBBBBIIIIIIIIQQQQQQQQQKKKKKDDDDDDLLLLLLLLYYYYYOOOOOOOOOOOPPPPPPKKKKPPPPEEEEEEEOFFFFFFFFFFFFFFFFFZZZZZZZJJJNNNN\n" +
            "TTYTTTTTGGGGGGOOOOOOOXXXXXXXXXXXXBIIIIIIIIIQQQQQQQQQKKKDDDDDDDDDLLLLLYYYYYYYOOOOOOOOOOOPPPPPPPPPPPPEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFZZOZZJNNNNN\n" +
            "TTTTTTTGGDDGGOOOOOOOOXXXXXXXXXXIIIIIIIIIIIIQQQIQQQQQKKKDDDDDDDDLLLLYYYYYYYYYOOOOOOOOOOPPPPPPNNPPPPPPEEEEEEEEEQFFFFFFFFFFFFFFFFFFFZZDDZDDNNNN\n" +
            "TTTTTTTTGGOOOOOOOOOOOXXXXXXXXXXRIIIIIIIIIIIIIIIQQQKKDDDDDDDDDDDLLLLLYYYYYYYYOOOOOOOOOOOPPPPPNNPPPPPPPEEEEEEEEQEFSRFFFFFFFFFFFFFFFZDDDDDDNNNN\n" +
            "TTTTTTTTTTOOOOOOOOOOOOOXXXXXXXXXXIIIIIIIIIIIIIQQQQQMMMMMMMDDDDDMMMMMMMHHYYYYOOOOOOOOOOOPPPNNNNPPNPPOPEEEEEEEEEERRRFFFFFFFFGZFZFDDDDDDDDNNNNN\n" +
            "TTTTTTTTTTTOOOOOOOONONNNNXXXXXXXXIIIIIIIIIIIIIIQQQQMMMMMMMMMMMMMMMMMMMHYYYOOOOOOOOOOOOOPPPNNNNNNNPOOPOOEEEEEEFFRRRZZFFFFFZZZZZZDDDDDDDDTNNRN\n" +
            "TTTTTTTTTTTQOOOOOOONNNNNXXXXXXXXIIIGIIIIIIIIIIIPPQMMMMMMMMMMMMMMMMMMMMHYYYOOOOOOOOOOOOOPPNNNNNNNNPOOOOOOEEORRRRRRRRZZZZLZZZZZZDDDDDDDDDDDDRR\n" +
            "TTTTTTQQQTTQOOOOOOODNNNNXNXXXXXXXXXGIIIIIIWIINIMMMMMMMMMMMMMMMMMMMMMMMHYYYYYOOOOOOOOOOONNNNNNNNNNPOOOOOOOOOORRRRRRRZZZZZZZZZZDDDDDDDDDDDDDDD\n" +
            "TTTTTTQZQQQQQOOOFOOONNNNNNXXXGGXXXXGIIIWWWWWWWIMMMAMMMMMMMMMMMMMMMMMMMHYYYYOOOOOOOOOOOOONNNNNNNNNPOOOOOOOOOORRRRRRRZZZZZZZZZZDDDDDDDDDDDDQQD\n" +
            "TTTTTQQQQQQQQOEOOONFNNNNNNXGXGGXXXGGGWWWWWWWNWNNMMMMMMMMMMMMMMMMMMMMMMHYYYYOOOOOOOOOOMOMMNNNNNNMMOOOOOOOOOORRRRRRRRRZZZZZZZZZDAADDDDDDDDDQQQ\n" +
            "TTTTTQQQQQQQQOQQQONNNNNNNNGGXGIGGGGGGWWWWWWWWWNNFAAMMMMMMMMMMMMMMMMMMMYYYTTHHOOOOOOOMMMMMNNNNNNMOOOOOOOOOOOORRRRRRRZZZZZZZZZZZAPDPPPPDDDDQQQ\n" +
            "TATTTQQQQQQQQQQQQQQQQNNNNNGGGIIIIGGGGGWWWWWWWWWNFAAMMMMMMMMMMMMMMMMMMMYTTTTHHHOOOOOOMMMMMNMMNNMMOOOOOOOOOOOORRRRRRZZZZZZZZZZPPAPPPPPPDDDQQQQ\n" +
            "AAATTQQQQQQQQQQQQQQQGNNGGGGGIIIIIGIGZZZWWWWWWWWFFAAAAAAAPMMMMMMMMMMMMMTTTTTHHHOOOOOOMMMMMNMMMNMMOOOOOOOOOOOOVRZZRRZZZZZZZZZZPPPPPPPPPPDPQQQQ\n" +
            "AAAATQQQQQQQQQQQQQQQGGGGGGGIIIIIIIIGZZZWWWWWWWFFFFAFFAAAPMMMMMMMMMMTTTTTTTTHHHOUUUUOMMBBMMMMMMRRRRRRRROOOOOOOOZRRZZZZZZZZZZZPPPPPPPPPPPPQQQQ\n" +
            "AAAAAQGQQQQQQQQQQQQGGAAAAIIIIIIIIIIIZZZWWWWWFFFFFFFGFAAAPPPPPPPPPPDTTTTTTTTTTTOUUUUUBBLBMMMMMMRRRRRRRROOOOOOOOZZZZZZZZZZZZZZPPPPPPPPPPPPQQQQ\n" +
            "AAAAAAQQQQQQQQQQQQQAGGAAAIIIIIIIIIIWZZZWWWFFFFFFFFFFFAFAFPPPPPPPTTTTTTTTTTTTTTUUUUUUBBBBBBBBMMRRRRRRRROOOOOOODZDDDZZZZZTTZZPPPPPPPPPPPPPPQQQ\n" +
            "AAAAAAAAQQQAAAQQQQQAAAAAAAIIIIIIIIIWZZZWWFFFFFFFFFFFFFFFFPPPPPPPPTTTTTTTTTTTTTTTUUUUUBBBBBBMMMRRRRRRRROOOOOODDDFFDDZZZTTTTZPPPPPPPPPPPPPPPQQ\n" +
            "KAAAAAAAAQAAAAAWWWAAOAAAAAIIIIIIIIIIZZZWWWFFFFFFFFFFFFFFFFPPPPPPPTTTTTTTTTTTRRRRZUZZUBBBBBBMMMRRRRRRRROOOOOOVDDFDDDZZTTTTTTTPPPPPPPPPPPPPQQQ\n" +
            "KAAAAAAAAAAAAAAAAANNAAAABBIIIIIIIIIIZZZWWWWFFFFFFFFFFFFFFFPPPPPPPTTTTTTTTTTTRRRRZUZZUUBBBBBBMMRRRRRRRROOOOORRRRRRRRDZTTTTTTTPPPPPPPPPPPPPQQQ\n" +
            "AAAAAAAAAAAAAAAAANNNNBBBBBBIBIBIIIIIZZZWFFWFFFFFFFFFFFFFFPPPPPPPPOOTTTTTTTTTTTTZZZZRRRRRRRRRRRRRRRRRRROOOVVRRRRRRRRDDTTTTTTTPPPPPPPPPPPPPPQQ\n" +
            "AAAAASAAAAAAAAWWWBBBBBBBBBBBBMBBRIIWZZZWFFFFFFFFFFFFFKFFBPPPPPPOOOOXXTTTTTTTTTTZZZZRRRRRRRRRRRRRRRRRRRVVVVVRRRRRRRRDDTTTTTTTPPPPPPPQPPPQQQQQ\n" +
            "AAAAASAAAAAAAAWWWBBBBBBBBBBBBBBBWWZZZZZWFTFFFFFFFFKKKKFKPPPPPPPOOOOOXXTTTTTZZZZZZZZRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRDDTTTTTTTTPPPPPPRUPPQQQQQ\n" +
            "AAASSSAAAAAAAWWWWWBBBBBBBBBBBBBBWWZZZWWWFTTFFFFBKKKKKKKKPPPPPJOOOOOOOOTTTTTZZZZZZZZRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRSTTTTTTTTPPRRRRRRQQQQQQQQ\n" +
            "SAASSSSSAAAWWWWWBBBBBBBBBBBBBBBVVAZZZWWWMTTFFFFFKKKKKKKKPPPPPJJOOOOOOOTTTTOZZZZZZZZRRRRRRRRRRRRVVVVRRRRRRRRRRRRRRDDSSTTTTTTTTTEERRRRRRQQQQQQ\n" +
            "SSSSSSSWWWWWWWWWWWBBBBBBBBBBBBBBAAZZZXWMMMTMFFMMMKKKKKKKKPPPPPJOOOOOOOOOTTOZZZZZZZZRRRRRRRRRRRRVVVVRRRRRRRRRRRRRRDSSSTTTTTTTTTERRRRRRRRQQQQQ\n" +
            "SSSSSSSWWWWWWWWWWWWBBBBBBBBBBBBXXAZZZXMHMMMMMMMMMMKKKKKKKKKKPPPPOOOOOIOOOOODZZZZZZZZZZZRRRRRRRRVVKVRRRRRRRRRRRRRRSSSTTTTTTTTEEERRRRRRRQQQQQQ\n" +
            "SSSSSSSSWWWWWWWWWWBBBBBBBBBBTBBXXXZZZMMMMMMMMMMMMMKKKKKKKKKKPHOOOOOOOIOOOOODZDDZZZZZZZZRRRRRRRRVVKVRRRRRRRRRRRRRRSSSSSSSTEETEEEERRRRQQQQQQQQ\n" +
            "SSSSSSSSWWWWOOWWWWWBBBBBBBBBTTBXXXZZZMXMMMMMMMMMMMMKKKKKKKKKOOOOOOOIIIOOODDDDDDZZDZZZZZRRRRRRRRVVVVRRRRRRRRRRRRRRSSSSSSSTEEEEEEELLBRQQQQQQQQ\n" +
            "SSSSSSSSWWWOOWWWWWBBWVNBBBNBBBBXXXXMMMMMMMMMMMMMMMMMKKKKKKHKHOOOIIIIIIIOODDDDDDDZDZZZZZRRRRRRRRVVIVRRRRRRRRRRRRRRSSSSSSSTEEEEEEELLLRQLQQQQQT\n" +
            "SSSSSSSWWOOOOWWWWWWWWVBBBBNBBBBXBBBGGGMMMMMMMMMMMMKKKKKKKKHHHHOOIIIIIIIDDDDDDDDDDDZZZZZQQQQQQQQQIIVRRRRRRRRRRRRRRSSSSSSSEEEEEEEEELLLLLTTTTTT\n" +
            "SSSSSSWWOOOOOWWWVVVVVVVEBBDDBSBBBBBBBBBMMMMMMMMMMMKKKKKKKKHHHHIIIIIIIIIDDDDDDDDDDDDZZQQQQQQQQQQIIIIIUUURRRRRRRRRRSSSSSSREEEEEEEEELLLLLLLTTTT\n" +
            "SSSSSSWOOOOOOOWWWVVVVVVVDDDDBSBBBBBBBBBBMMMMMMMMMKKKKKKKHHHHHHIIIIIIIIIEDDDDDDDDDDXDQQQQQQQQQQQIIIIIUUUUUUUIISSSSSSSSSSRRERRRREEEELLLLLLTTTT\n" +
            "SSSSSSWWOOOOOOOOOVVVVVVVDDDDBBBBBBBBBBBBMMMMMMMMMKKKKKKKHHHHHHHIIIHIIIFDDDDDDDDDDDDDQQQQQQQQQQIIIIIIIUUUUUUIISISSSSSSSSRRERRRREEEELLLLLLTTTT\n" +
            "SSSSSSWWOOOOOOOOOOOVVVVVDDDDBBBBBBBBBBEEEMMMMMMMMKKKKKKPKHHHHHHIHHHHHHDDDDDDDDDDDDDDDDQQQQQQIIIIIIIIIUUUUUUIIIIISSSRRSXRRRRRRRRRBEELLLLLTTTT\n" +
            "SSSSSWWWOOOOOOOOOOOVVVVVDDDDBBBBBBBBCBBEEMMMMOOOKKKKKKKKKKKKKHHHHHHHDDDDDDDDDDDDDDDDDDQQQQQQMIIIIIIIUUUUUUIIIIIIIRRRRSSRRRRRRRRBBBBBLLLTTTTT\n" +
            "SSSSSSOOOOOOOOOOOOOVVVVVDDDDDBBBBBBBBEEEEMEMMOOKKKKKKKKKKKKKKHHHHHHHDDDDDDDDDDDDDDDMODQQQQQMMIIIOOOIIUUUOUIIIIIIIIRROOOOOOOOOORBVBBBLLLLLTTG\n" +
            "SSSSSSSOOOOOOOOOOBOVVVVVDDDDDEEBBBBBBEEEEEEOOOOOKKKKKKFKKKKKKHHHHHHHHDDDDDDDDDDDMDDMMMQQQQMMMMMIOIIIIIUUUUUIIIIIIIRROOOOOOOOOORYBBBBLBBLLLLG\n" +
            "KSSSSSOOOOOOOOOOOBOFVVDDDDDDDDEBEEBEEEEEEEEEOEOOKLKKKKKKKKKKKHHHHHHDDDDDDDDDDDDDMMMMMMMMQZMMMMMMOOOIIIIUUUIIIIIIIIRROOOOOOOOOOYYBBBBBBBLLLGG\n" +
            "KSSKKKXXXOOOOOOOOOFFVVDDDDDDDEEEEEEEEEEEEEEEEEEOOKKKKKKKKKKKKKHHHHHDFDDDDDDDDDDDMMMMMMMMZZMMMDDMOOOIIIIUUIIIIIIIIIIROOOOOOOOOOYYBBBBBBQIIIIG\n" +
            "KSKKKKXXXOOOOOOOHMFFVVDDDDDDDDEEEEEEEEEEEEEEEEEOOKKKKKKKKKKKKKHHHHHDFDDDDDDDDDDEEMMMMMMZZZMMMMMOOOOOOIIUIIIIIIIIIIIROOOOOOOOOOYYBBILBQQIIIII\n" +
            "KKKKKKKKKQOOOOOOOMFFVVVDDDDDEEEEEEEEEEEEEEEEEEEEOSSSSKKKKKKKKKHHHHHMMUDDDDDDDDTEEEMMMMMMZMMMMMOOOOOOOIIIIIIIIIIIIIRNOOOOOOOOOOYBBBIBBBBIIIII\n" +
            "KKKKKKKBBGGUOOOOOMMFMGDDDDDDEEEEEEEEEEEEEEEUEEEEOSSSSKKKKKKKQKKHHHHMMUUDDDDDDDTTTTTMMMMZZZZMMMMOOOOOOOOIIIIIIIIIIIRRRRRROOOOPYYIBIIIBIIIIIII\n" +
            "KKKKKKKBYYGGCCCODMMMMDDDDDDDEEEEEEEEEEEEEEEEEEEEOSSSSKSSSKSKKHHHHMMMMMUUTDDDTQTTTTMMMMMMZZZMMMOOOOOOOBOIIIIIIIIIIIIIRRRROOOOYYYIIIIIIIIIIIII\n" +
            "KKKKKKKYYYGGCCCTTTTTTPPDDDDDEEEEEEEEEEEEEEEEEEEEOSSSSSSSSSSSSHHHHHMMMMMMTTTTTTTTTXMYMGMMMMZZOOOOOOOOOOIIIIIXIIXXIIIIIIIIMPPPPYIIIIIIIIIIIIII\n" +
            "KKKKKKEEYYGGCCCTTTTTTTTDDDDDOCCEECCEEEEEEEEEEEEOOSSSSSSSSSSSSHHHHHMQYMMMTTTTTTTTTTTTLGGGOOOOOOOOOOIOOAIIIIIXXXXXXIIIIIMMMMPPPPIIIIIIIIIIIIII\n" +
            "KKKKKKEEYYYGCCCTTTTTTTTDDDUDCCCVVCCEYYEEEEEEEEEEOOSSSSSSSSSSSYYYYYYYYYPPPPTTTTTTTTSSGGGGGGGOOOOOOIIIOIIIIIIXXXXXXXIIIMMHMMMPMPMIIIIIIIIIIIII\n" +
            "KKKKKFYYYYYYCCCTTTTTTTTQDDDDCCCCCCCCYYYYEEEEEEEWOWSSSSSSSSSSYYYYYYYYYYYPPPPTTTTTTTKKBBGGGGGGGOOOOIIIIIIIIAAXXXXXXXIMMMMMMMMMMMMMIYIIIIIIIIII\n" +
            "KKKDFFYYCUCCCCCCTTTTTTTTWWWCCCCCCCCCCCYYYEEEEESWOWWWSSSSSSSSYYYYYYYYYYYYPPPTTTTPPPKKKBBGGGGGGOOOOIIIIIIIIAIXXXXXMIIIIMMMMMMMFFFFFIIIIIIIIIJJ\n" +
            "DDDDFFFFUUUUCCCCTTTTTTTTWWWCCCCCCCYYYYYYYEEEEEEWWWWWWWWSSSSVVYYYYYYTYYPPPPPPPPPPKPKKKBBKGQGGGOOIIIIIIIIDDDDDDDDDDMMMMMMMMMMHHFFFFIIFIIIIIJJJ\n" +
            "DDDDDFFUYUUUUTTTTTTTTTTTWWWCCCCCCCYYYYYYYYEEEEKWWWWWWWWWSSSVVYYYYYYYYPPPPPPPPPPPKKKKKKKKQQIGGOIIIIIIIIIDDDDDDDDDDMMMMMMMMMMHHHFFFFFFIIIIIIIJ\n" +
            "DDDDDFFUUUUUWTTTTTTTTTTTTTWWCCCCCCCYYYYVVEEVEEKWWWWWWWWWWWSVVYYYYYYYPPPPPPOPOPOOKKKKKKKKKQIIIIIIIIIIIIIDDDDDDDDDDMMMMMMMMMMMHFFFFFFFFFFIIFIP\n" +
            "DDDDDDDCCUUTTTTTTTTTTTTTTTWWCKCCCYYYYVVVDEVVEEKVWQQQQQQWWWSVVVYYYYPPPPPPPPOPOOOKKKKKKKKKKQIIIIIIIIIIIIIDDDDDDDDDDMMMMMMMMMMHHHFFFFFFFFFFFFPP\n" +
            "DDDDDDDCUUUTTTTTTTTTTTTTTTTWWMMYYYYYYVVVVVVVVVVVVQQQQQQWWWNNNNYYYYYPPPPPOOOOOOKKKKKKKKKRRIIIIIIIIIIIIIHDDDDDDDDDDMMMMMMMMMMMMFFFFFFFFFFFFFFP\n" +
            "DDDDDDDDUUUTTJTTTTBTTTTTTTTMMQMMMYYYYVVVVVQQQQQQQQQQQQQNBNNNNNNNNNPPPPPPOOOOOOOOKKKKKKKRRRIIIIIIIIIIIAHDDDDDDDDDDMMMMMMMMMMQRFFFFFFFFFFFFPPP\n" +
            "DDDDDDDDJUUJJJTTBBBBTTTTTTSMMMMMMYYYYVVVVVQQQQQQQQQQQQQNNNNNNNNNNNNPPPPPPOOOOOOOOOOJKKKGGIIIIIIIIIIIAAADDDDDDDDDDFMZMMMMMMMRRRRFFFFFFFFFPPPP\n" +
            "DDDDDDJJJJUJJBQBBBBBTTTTTTSMMMMMMYYYQQQQQQQQQQQQQQQQQQQGGNNNNNNNNNNNPPPPOOOOOOOOOOOOGGGGGIIIIIIIIIIAAAADDDDDDDDDDFFZMMMMWMMMRRRFFFFFFFFFPPPP\n" +
            "NDDKDDKJJJJJBBBBBBBTTTTHBTTMMMMMMYYYQQQQQQQQQQQQQQQQQQQGNNNNNNNNNNNNPPPOOOOOOOOOOOYOGGGGGIIIIIIIIIAAAAADDDDDDDDDDFFFFMMMMMMMRRFFFFFFFFFFPPPP\n" +
            "KDDKKDKWWWJJJBBBBBBBBBBBBMTMMMMMMYYVQQQQQQQQQQQQQQQUGGGGGNNNNNNNNNMNNPOOOOOOOOOOOOYGGGGGGYIGIIIIIAAAAAAAAAAAFFFFFFFFFFFSRRRRRRRPRFFFFFFFPPPP\n" +
            "KKKKKKKWWWJJJBBBBBBBBBBBBBBMMMMMMYMOVVVVVQQQQQQQQQUUGGNGNNNNNNNZZPZNZZNNOOOOOOOOOOOGGGGGGGGGGIIIAAAAAAAAAAAAAFFFFFFFFFFRRRRRRPPPPFFFPPPPPPPP\n" +
            "KKKKKKKWWWWJJBBBBBBBBBBBBBBBMMOOMMMOOVVVVQQQQQQUTUUUUUNNNNNNNNZZZZZZZNNNNOCOOOOOOOGGGGGGGGGGGJIAAAAAAAAAAAAAAFFFFFFFFFFFFRRPPPPPPPFPPPPTPTTT\n" +
            "KKKKKKKWWWWJJBBBBBBBBBBBBBBBBBBOOMOOOOIVGQQQQQQJZUUMMMNNNNNFNNZZZZZFZZNNNOCOOOOOOOGGGGGGGGGGGJJAAAAAAAAAAAAAAAAFFFFFFFFVVRPPPPPPPPPPPPTTTTTT\n" +
            "KKCKKKKWWWMMJBBBBBBBBBBBBBBBBBBOOOOOOGGGGQQQQQQZZZZZZMMNNNNFNNZZZZZZZZZNNNCOOWOVOGGGLLGGGGGJGJJAAPAAAAAAAAAAAZSSFFFFFFVVVVPPPPPPPPPPPPTTTTTT\n" +
            "KKCKMKKWWWMMMMBBLBBBBBBBBBBBBBBOOOOOOGGGGQQQQQQZZZZCCNNNFNNFFFFFZZZZZZZNNNCOOOLLLGGGLLLLLLJJJJFFFFAAAAAAAAAAASSSSFFFFVVVVVVPPPPPPPPPPTTTTTTT\n" +
            "CCCMMPMMMZMMMMBBVBBVVVBBBBBBBBBOOOOOOGGGGQQQQQQHZZZZZNNNFNFFFFFEZZZZZZZZNNCOCCCLLLLLLLLLLLLLJFFFFFDAABAKAKKKBKSSSSFFVVVVVOOPPPPPPPPPPTTTTTTT\n" +
            "CCCMMMMMMMMMMVVVVVVVVVVBBVBBBBOOOOOOOGGGGQQQQQQGZZZZANNGFFFFFFFFZZZZZZZZCCCCCCCLLLLLLLLLLLLLJJFFFFFKQKKKKKKKKKSSSSSSVVVOOOZPPPPPPPPPPTTTTTTT\n" +
            "CCCMMMMMMMMMMAAVVVVVVVVVVVOOOOOOOOOGGGGGGQQQQQQRZZZFAAAFFFFFFFFFFZZZZZZZCCCCCCCCLLLLLLLLLLLLLFFFFFFKKKKKKKKKKKKKSSSSSVVOOOZPPPPPPPPITTTTTTTT\n" +
            "KCMMMMMMMMAAMAAVVTVVVTVVOOOOOOOOOOOGXGGGGQQQQQQZZRZFFFFFFFFFFFFFFFZZZZZZCCCCCCCCLLLLLLLLLLLLLLFFFFFXKKKKKKKKKKKKKKSVVVVVOSPPPPPPPPIIITTTTTTT\n" +
            "KCKMMMMMMAAAAAAATTTVTTTOOOOOOOGOOGGGGGGGGGGGGGRRRRRFFFFFFFFFFFFFFIFZZZZZCSSCCCCCLLLLLLLLLLLYLFFFFFFFQKKKKKKKKKKKKKKKVVVVOOVVUPPPPIIIITTTTTTT\n" +
            "KKKKMMKMMAAAAAAAATTTTTTTTTTOOOGOGGGGGGEEGGGGGGGRRFFFFFFFFFFFFFFFFFFZZZZZCSCCCCCCLLLLLLLLLLLLLOOFFFFFQKKKKKKKKKKKKKKKKVVOOVVVPPPPPIIITTTTTTTT\n" +
            "KKKKKKKKMAAAAAATTTTTTTTTTTTTOOGGGGGGGGGGGGGGGGGRFFFFFFFFFFFFFFFFFFFZZZZVCCCCCCCCCLLLJJJJJJJJJOQFQQQQQQKKKKKKKKKKKKKQVVVOOVVVVPVVIIIIFTTTTTTT\n" +
            "KKKKKKKKKKKAAAATYRTTTTTTTTTTYYYGGGGGGGGGGGGGGGRRRRFFFFFFFFFFFFFFFFFZZZZVCCCCCCCCCCLLJJJJJJJJJQQQQQQQQKKKKKKKKKKKKKKKKKVVVVVVVPPVIIIIFFTTNTTD\n" +
            "KKKKKKKKKKKAAAARRRTTTTTTTTYYYYYUGGGGGGGGGGGGGGRVRVZAFFFAAAFFFNFTFFFKKSSCCCCCCCCCCCCCJJJJJJJJJOQQQQQQQKKKKXXXXKKKKKKKKKVVVVVVVVVVIFFFFFFFNFFF\n" +
            "KKKKKKKKKKKAAAARRRRTTTTRRRRLYYGGGGGGGGGGGGGGGRRVVVAAFFAAAAAFFNNSSSFFSSSSCCCCCCCCCCHHJJJJJJJJJOQQQQQNQKKKKKXXXKKKKKKKKKKVVVSVVVVFFFFFFFFFFFFF\n" +
            "KKKKKKKKKKKAAAARRRRRTRRRRRRRYYYGGGGGGGGGGGGGGRRVVVAAAAAAAAAFFNSSSSSSSSSSSCCCCCCCCCHZJJJJJJJJJJJJJNNNNKKKKKXXXXKKKWWDDKVVVVSVVVVSSSSFFFFFFFFF\n" +
            "HKKKKKKKKAAAAARRRRRRRRRRRYYAYYYYGGGGGGGGGGGGRRVUVVPAAAAAAAAWSSSSSSSSSSSSSCCCCCCCHHHHJJJJJJJJJJJJJJJNNNNKKXXXFFFKWWDDDKVVVVSSVVVSSFSSFFFFFFFF\n" +
            "HKKPKKKKAAAAAARHRRRRRRRRRRYYYYYYYGGGGGGGGGVVVVVVVVPAAAAAAAAAAAASSSSSSSSLLCCCCCCCHHHHJJJJJJJJJJJJJJJNNNNNNNNXNFFDWWDDDDVMVVSSSUVSSFFFFFFFFFFF\n" +
            "HCCCKKKAAAAGAARRRRRRRRRRRLYAYYYYYYGGGGGGGGVVVVVVVVVAAAAAAAAAASSSSSSSSSSLCCCCCCCCCCHIIIJJJJJJJJJJJJJNNNNNNNNNNAADDDDDDUMMMXXSSUUFFFFFFFFFFFFF\n" +
            "HCCCCKAAAAGGGGRRRRRRRRRRRLYYYYYYYYYRGGGGGZVVVVVVVVVAAAAAAAAAAASCCCCCCCCCWCCCCCCCYCHYYYJJJJJJJJJJJJJNNNNNNNNNNAWDDDDDDDDMMMMSSUMMFFFFFFFFFFFF\n" +
            "HCCHHKGGGGGGGGGRRRRRRRRRRRPYYYYYYYRRRRRVVVVVVVVVVVVAAAAAAAAAAASCCCCCCCCCHCHCCCZCYCYYYYJJJJJJJJJJJJJNNNNNNNNNNAWDDDDDDDDDMMMMMMMMFFFFFFFFFFFF\n" +
            "HHHHHHHGGGGGGGGRRRRRRRRRRRPPYYYYYRRRRRRRRRVVVVVVAAVAAAAAAAAAAAACCCCCCCCCHHHHHHZYYYYYYYJJJJJJJJJJJJJNNNNNNNNNNAAOOOODDDDMMMMMMMMMMMFFFFFFFFFF\n" +
            "HHHHHHHGGGGGJGGRRRRRRRRRPPPPYYKYYRRRRRRRRRVVVVVVAAAAAAAAAAAEASSCCCCCCCCCHHHHHYYYYYYYYYYYYYYYYPPPJJJNNNNNNNNAAAAOOOODDDMMMMMMMMMMMFFFFFFFFFFF\n" +
            "HHHHHHHGGGGGGGGRRRRRRRRRRPPFYYKFYFFFRRRRRVVVVVVVAAAAAAAAAAAESSSCCCCCCCCCHHHWHHHYYYYYYYYYYYYPPPPPJJJPPPPNNNAAAAAAAAODHMMMMMMMMMVBFFFFFFFFFFFF\n" +
            "HHHHHHGGGGGGTTTRYRRRRRTTFTPFFFKFFFFFRRRRRRXVVVVAAAAAAAAAAADSSSSCCCCCCCCCHHHHHHHYYYYYYYYYYYYYYPPPJJJPPPPPPPAAAAAAAAADHHMMMMMMMMMBFFFFFFFKKKKK\n" +
            "HHHHTGGGGGGGTTTTRRRRRRTTTTTFFFFFFFFFRRRRRXXVXXVVVAAAAAAAAADDDDHHHHHCCCCHHHHHHHHHYYYYYYYYYYYYYPPPPPPPPPPPPFAAAAAAAAAAHHHHHMMMMDBBFFBBBKKKKKKK\n" +
            "HHHHTTTGTTTTTTTTRRPRRRPPOTTFFFFFFFFFRRRRXXXXXXVVVVVAAAAAAADVDDDHHHHCCCCHHHHHHHHHYYYYYYYYYYHYPPPPPPPPPPPPPAAAAAAAUADAHHHHHHMHHDBBBFBBBBUUKKKY\n" +
            "HHHHTTTTTTTTTTTTPRPRGGPOOOFFFFFFFFFFFRRRXXXXVVVVVVVAAAVAAAVVDDVHHHHCCCCCCCCCCEYYYYYYYYYYYYYYPPPPPPPPPPPPPAAAAAAAAAAHHHHHHHHHDDDDBBBBBBUUKKKK\n" +
            "HHHTTTTTTTTTTTTTPPPPPPPOOFFFFFFFFFFFFFFXXXXXVVVVVVVAAVVVVVVVVVVHHHHCCCCCCCCCCTYEYYYYYYYYYYYPPPPPPPPPPRPYPAAAAAAAAAAAHHHHHHHDDDDBBBBBBUUUKKKK\n" +
            "HHHHYYTTTTTTTTTPPPPPPPPPOOFFFFFFFFFFFFFMMXXXXXVVVVVVVVVVVVGVVWWWHHHCCCCCCCCCCTEEEEEYYYYYYXYPPPPPPPPPBPPPPPAAAAAAAAAHHHHHBBBDYDBBBBBBUUKKKKKK\n" +
            "HHHHYYYTTTTTTTTPPPPPPPPOOOFFFFFFFFFFFFFMMXXXXXXVVVVVVVVVVVVVVWWWHHHHCCCCCCCCCTEEEEEYYYYQQQQDPPPPPVVPPPPPPPAAAAAAWAHHHHHHBBBYYYBBBBBBBUKKKKKK\n" +
            "HYYYYYYYYYTTPPPPPPPPPPPPPPFFFFFFFFFFFFMMMXXXXXVVVVVCCCCVVVRRRHHHHHHHCCCCCCCCCTTTTTTYQQYYQQQDDDDPPPVMPMMPPPDAAAAAAAHHHHHBBBBBYYBBBBBBUUUUKKKK\n" +
            "HHYYYYYYYYYPPPPPPPPPPPRPPPFFRFFVVFFFFVMMXXXXCVVVCCVCXVVVVVRRRHRRHHHSCCCCCCCCCTTTTTTYQQQQQQQDDDDDPVVMMMMMPMAAAAAAAAHHBBBBBBBYYBBBBBUUUUUUKKKK\n" +
            "HYYYYYYYYYYPPPPPPNNNAPRRRRRRRVVVVVFAVVVMMMXCCCVVCCCCCVVVVVRERRRRRHSSCCCCCCCCCTTTTTTTQQQQQQQQDDDDPVVMMMMMMMMAWAAOOSSSSBBBBBYYBBBBBBUUUUUUUKTK\n" +
            "YYYYYYYYYYYEEPPPPPNAAPPRRRRRVVVVVVFVVVVVCCXCCCCDCCMMMMMMVVVERRRRRSSSCCCCCCCCCTTTTTQQQQQQQQQQQDDDPZVVMMMMMMMMMMASSSSSVVBBBBBBBBBBBUUUUUUEETTE\n" +
            "MYYYYYYYYYYYEPPPPPPAAAAARRRRVVVVVVVVVVVVVCCCCCCDCCCCCMMMVDDEEEERRSSSCCCSNTTTTTTTTQQQQQQQQQQQQDDDDZZMMMMMMMMMMMSSSSSSSVBXBBBBBBBBBEEUUUUETTEE\n" +
            "MYYYYYYYYYYEEPDDAPAAAAAEAAAAVVVVVVVVVVVVVCCCCCCCCCCCCMCCVDDEEEERRSSSCCCSSTTTTTTTYQQQQQQQQQQQQQDDDZZMMMMMMMMMMMMSSSSSSSXXBBBBBBBBBYEEUEEEEEEE\n" +
            "MYYYYYYYYYYYEAAAAAAAAAAAAAAAVVVVVVVVVVVVVCCCCCCCCCCCCCCCCDEEEEERESSSCCCTTTTTTTTTTQQQQFQQQQQQQQDZZZZZZMZMMMMMMSSSSSSSXXXXXBBBBBBBLEEEEEEEEEEE\n" +
            "MYYYYYYYYYYYAAAAAAAAAAAAAAAAVVVVVVVVVVVVCCCCCCCCCCCCCCDDDDDDEEEEEESSCCCSTTTTTTTTTQQQQFFQQQQQQQZZZZZZZZZZMMMMMMMYSSSSXXXXXXGBBBBEEEEEEEEEEEEE\n" +
            "MYYYYYYYYYYMMAAAAAAAAAAAAAAAVVVVVVVVVVVCCCCCCCCCCCCCDDDDDDEEEEEEEESSSSSTTTTTTTTTTTFFFFFQQQQQQQZZZZZZZZZMMMMMMMWSSWWXXXXXXXGGMBBEEEEEEEEEEEEE\n" +
            "MYYYYYYYYMMMMMAAAAAAAAAAAAAAVVVVVVVVVVCCCCCCCCCCCCCCCDDDDDEEEEEEEESSSSSTTTTTTTTTTFFFFFFFFQQQQQQQZZZZZZJMMMMMMMWSSWXXXXXXXXGMMMMEUEEEEEEEEEEE\n" +
            "MYYYYYYMMMMMMMAAAAAAAAAUAAVVVVVVVVVVVVCCCCCCCCCCCCCCDDDDDDDEEEEEEEESRSEEETTTTYTFFFFFFFFFFQQQQQQQZZZZZZJMMMMMWWWWWWWXXGXGGGGGMMMEEEEEEEEEEEEE\n" +
            "YYYXXYYMMMMMMMAAAAAAAAAAAIVVVVVVVVVVVVVCCCCCCCCCCCCCDDDDDDDEEEEEEEEEEEEEETTTTYTFFFFFFFFFFQQQZZZZZZZZZJJJMMMMMMWWWWWXGGGGGGGMMMMEEEEEEEEEEEEE";


}
